//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.mesEmployeeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mesEmployeeService.ImesEmployeeSVC")]
    public interface ImesEmployeeSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesEmployeeSVC/Insert", ReplyAction="http://tempuri.org/ImesEmployeeSVC/InsertResponse")]
        int Insert(App.Model.mesEmployee model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesEmployeeSVC/Insert", ReplyAction="http://tempuri.org/ImesEmployeeSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesEmployee model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesEmployeeSVC/Delete", ReplyAction="http://tempuri.org/ImesEmployeeSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesEmployeeSVC/Delete", ReplyAction="http://tempuri.org/ImesEmployeeSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesEmployeeSVC/Update", ReplyAction="http://tempuri.org/ImesEmployeeSVC/UpdateResponse")]
        bool Update(App.Model.mesEmployee model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesEmployeeSVC/Update", ReplyAction="http://tempuri.org/ImesEmployeeSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesEmployee model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesEmployeeSVC/Get", ReplyAction="http://tempuri.org/ImesEmployeeSVC/GetResponse")]
        App.Model.mesEmployee Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesEmployeeSVC/Get", ReplyAction="http://tempuri.org/ImesEmployeeSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.mesEmployee> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesEmployeeSVC/ListAll", ReplyAction="http://tempuri.org/ImesEmployeeSVC/ListAllResponse")]
        App.Model.mesEmployee[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesEmployeeSVC/ListAll", ReplyAction="http://tempuri.org/ImesEmployeeSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.mesEmployee[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImesEmployeeSVCChannel : App.MyMES.mesEmployeeService.ImesEmployeeSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImesEmployeeSVCClient : System.ServiceModel.ClientBase<App.MyMES.mesEmployeeService.ImesEmployeeSVC>, App.MyMES.mesEmployeeService.ImesEmployeeSVC {
        
        public ImesEmployeeSVCClient() {
        }
        
        public ImesEmployeeSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImesEmployeeSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesEmployeeSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesEmployeeSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.mesEmployee model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesEmployee model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.mesEmployee model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesEmployee model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.mesEmployee Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesEmployee> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.mesEmployee[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesEmployee[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
