//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.PartSelectService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PartSelectService.IPartSelectSVC")]
    public interface IPartSelectSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/MyTest", ReplyAction="http://tempuri.org/IPartSelectSVC/MyTestResponse")]
        double MyTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/MyTest", ReplyAction="http://tempuri.org/IPartSelectSVC/MyTestResponse")]
        System.Threading.Tasks.Task<double> MyTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/P_DataSet", ReplyAction="http://tempuri.org/IPartSelectSVC/P_DataSetResponse")]
        System.Data.DataSet P_DataSet(string S_Sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/P_DataSet", ReplyAction="http://tempuri.org/IPartSelectSVC/P_DataSetResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> P_DataSetAsync(string S_Sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/ExecSql", ReplyAction="http://tempuri.org/IPartSelectSVC/ExecSqlResponse")]
        string ExecSql(string S_Sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/ExecSql", ReplyAction="http://tempuri.org/IPartSelectSVC/ExecSqlResponse")]
        System.Threading.Tasks.Task<string> ExecSqlAsync(string S_Sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluPartFamilyType", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluPartFamilyTypeResponse")]
        System.Data.DataSet GetluPartFamilyType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluPartFamilyType", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluPartFamilyTypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetluPartFamilyTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetServerIP", ReplyAction="http://tempuri.org/IPartSelectSVC/GetServerIPResponse")]
        string GetServerIP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetServerIP", ReplyAction="http://tempuri.org/IPartSelectSVC/GetServerIPResponse")]
        System.Threading.Tasks.Task<string> GetServerIPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluPartFamily", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluPartFamilyResponse")]
        System.Data.DataSet GetluPartFamily(string PartFamilyTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluPartFamily", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluPartFamilyResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetluPartFamilyAsync(string PartFamilyTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesPart", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesPartResponse")]
        System.Data.DataSet GetmesPart(string PartFamilyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesPart", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesPartResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesPartAsync(string PartFamilyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesPartDetail", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesPartDetailResponse")]
        System.Data.DataSet GetmesPartDetail(int PartID, string PartDetailDefName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesPartDetail", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesPartDetailResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesPartDetailAsync(int PartID, string PartDetailDefName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluPODetailDef", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluPODetailDefResponse")]
        System.Data.DataSet GetluPODetailDef(int ProductionOrderID, string PODetailDef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluPODetailDef", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluPODetailDefResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetluPODetailDefAsync(int ProductionOrderID, string PODetailDef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesPartPrint", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesPartPrintResponse")]
        System.Data.DataSet GetmesPartPrint();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesPartPrint", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesPartPrintResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesPartPrintAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesLine", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesLineResponse")]
        System.Data.DataSet GetmesLine();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesLine", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesLineResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesLineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/mesLineGroup", ReplyAction="http://tempuri.org/IPartSelectSVC/mesLineGroupResponse")]
        System.Data.DataSet mesLineGroup(string LineType, int PartFamilyTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/mesLineGroup", ReplyAction="http://tempuri.org/IPartSelectSVC/mesLineGroupResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> mesLineGroupAsync(string LineType, int PartFamilyTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetsysStatus", ReplyAction="http://tempuri.org/IPartSelectSVC/GetsysStatusResponse")]
        System.Data.DataSet GetsysStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetsysStatus", ReplyAction="http://tempuri.org/IPartSelectSVC/GetsysStatusResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetsysStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesStationType", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesStationTypeResponse")]
        System.Data.DataSet GetmesStationType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesStationType", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesStationTypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesStationTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesRoute", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesRouteResponse")]
        System.Data.DataSet GetmesRoute();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesRoute", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesRouteResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesRouteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetRouteSequence", ReplyAction="http://tempuri.org/IPartSelectSVC/GetRouteSequenceResponse")]
        System.Data.DataSet GetRouteSequence(string RouteID, string StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetRouteSequence", ReplyAction="http://tempuri.org/IPartSelectSVC/GetRouteSequenceResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetRouteSequenceAsync(string RouteID, string StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesStation", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesStationResponse")]
        System.Data.DataSet GetmesStation(string LineID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesStation", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesStationResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesStationAsync(string LineID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesStationTypeByStationID", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesStationTypeByStationIDResponse")]
        System.Data.DataSet GetmesStationTypeByStationID(string StationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesStationTypeByStationID", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesStationTypeByStationIDResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesStationTypeByStationIDAsync(string StationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluSerialNumberType", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluSerialNumberTypeResponse")]
        System.Data.DataSet GetluSerialNumberType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluSerialNumberType", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluSerialNumberTypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetluSerialNumberTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetUnit", ReplyAction="http://tempuri.org/IPartSelectSVC/GetUnitResponse")]
        System.Data.DataSet GetUnit(string PartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetUnit", ReplyAction="http://tempuri.org/IPartSelectSVC/GetUnitResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUnitAsync(string PartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetUnit2", ReplyAction="http://tempuri.org/IPartSelectSVC/GetUnit2Response")]
        System.Data.DataSet GetUnit2(string PartID, string StationID, string POID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetUnit2", ReplyAction="http://tempuri.org/IPartSelectSVC/GetUnit2Response")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUnit2Async(string PartID, string StationID, string POID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetMachineHistory", ReplyAction="http://tempuri.org/IPartSelectSVC/GetMachineHistoryResponse")]
        System.Data.DataSet GetMachineHistory(string S_UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetMachineHistory", ReplyAction="http://tempuri.org/IPartSelectSVC/GetMachineHistoryResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMachineHistoryAsync(string S_UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetUnit_Search", ReplyAction="http://tempuri.org/IPartSelectSVC/GetUnit_SearchResponse")]
        System.Data.DataSet GetUnit_Search(string S_DateStart, string S_DateEnd, string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetUnit_Search", ReplyAction="http://tempuri.org/IPartSelectSVC/GetUnit_SearchResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUnit_SearchAsync(string S_DateStart, string S_DateEnd, string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetUnitComponent", ReplyAction="http://tempuri.org/IPartSelectSVC/GetUnitComponentResponse")]
        System.Data.DataSet GetUnitComponent(string S_UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetUnitComponent", ReplyAction="http://tempuri.org/IPartSelectSVC/GetUnitComponentResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUnitComponentAsync(string S_UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesUnitDetail", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesUnitDetailResponse")]
        System.Data.DataSet GetmesUnitDetail(string S_UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesUnitDetail", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesUnitDetailResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesUnitDetailAsync(string S_UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetHistory", ReplyAction="http://tempuri.org/IPartSelectSVC/GetHistoryResponse")]
        System.Data.DataSet GetHistory(string UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetHistory", ReplyAction="http://tempuri.org/IPartSelectSVC/GetHistoryResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetHistoryAsync(string UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesUnitState", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesUnitStateResponse")]
        System.Data.DataSet GetmesUnitState(string S_PartID, string S_RouteSequence, string LineID, int StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesUnitState", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesUnitStateResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesUnitStateAsync(string S_PartID, string S_RouteSequence, string LineID, int StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesSerialNumberOfLine", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesSerialNumberOfLineResponse")]
        System.Data.DataSet GetmesSerialNumberOfLine(string SNCategory, string PrintCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesSerialNumberOfLine", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesSerialNumberOfLineResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesSerialNumberOfLineAsync(string SNCategory, string PrintCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesSerialNumberByUnitID", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesSerialNumberByUnitIDResponse")]
        System.Data.DataSet GetmesSerialNumberByUnitID(string UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesSerialNumberByUnitID", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesSerialNumberByUnitIDResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesSerialNumberByUnitIDAsync(string UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetPO", ReplyAction="http://tempuri.org/IPartSelectSVC/GetPOResponse")]
        System.Data.DataSet GetPO(string S_PartID, string S_StatusID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetPO", ReplyAction="http://tempuri.org/IPartSelectSVC/GetPOResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPOAsync(string S_PartID, string S_StatusID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetPOAll", ReplyAction="http://tempuri.org/IPartSelectSVC/GetPOAllResponse")]
        System.Data.DataSet GetPOAll(string S_PartID, string S_LineID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetPOAll", ReplyAction="http://tempuri.org/IPartSelectSVC/GetPOAllResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPOAllAsync(string S_PartID, string S_LineID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetRoute", ReplyAction="http://tempuri.org/IPartSelectSVC/GetRouteResponse")]
        System.Data.DataSet GetRoute(string PartID, string S_RouteSequence, string LineID, int StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetRoute", ReplyAction="http://tempuri.org/IPartSelectSVC/GetRouteResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetRouteAsync(string PartID, string S_RouteSequence, string LineID, int StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetApplicationType", ReplyAction="http://tempuri.org/IPartSelectSVC/GetApplicationTypeResponse")]
        System.Data.DataSet GetApplicationType(string StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetApplicationType", ReplyAction="http://tempuri.org/IPartSelectSVC/GetApplicationTypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetApplicationTypeAsync(string StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluDefect", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluDefectResponse")]
        System.Data.DataSet GetluDefect(int DefectTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluDefect", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluDefectResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetluDefectAsync(int DefectTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluUnitStatus", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluUnitStatusResponse")]
        System.Data.DataSet GetluUnitStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluUnitStatus", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluUnitStatusResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetluUnitStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesUnitDefect", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesUnitDefectResponse")]
        System.Data.DataSet GetmesUnitDefect(string S_UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesUnitDefect", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesUnitDefectResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesUnitDefectAsync(string S_UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/uspSNRGetNext", ReplyAction="http://tempuri.org/IPartSelectSVC/uspSNRGetNextResponse")]
        System.Data.DataSet uspSNRGetNext(string strSNFormat, int ReuseSNByStation, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strNextSN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/uspSNRGetNext", ReplyAction="http://tempuri.org/IPartSelectSVC/uspSNRGetNextResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> uspSNRGetNextAsync(string strSNFormat, int ReuseSNByStation, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strNextSN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetPartDetailDef", ReplyAction="http://tempuri.org/IPartSelectSVC/GetPartDetailDefResponse")]
        System.Data.DataSet GetPartDetailDef(string SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetPartDetailDef", ReplyAction="http://tempuri.org/IPartSelectSVC/GetPartDetailDefResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPartDetailDefAsync(string SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_MachineRouteMap", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_MachineRouteMapResponse")]
        string Get_MachineRouteMap(string S_ToolSN, string S_ProductPartID, string S_RouteID, string S_StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_MachineRouteMap", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_MachineRouteMapResponse")]
        System.Threading.Tasks.Task<string> Get_MachineRouteMapAsync(string S_ToolSN, string S_ProductPartID, string S_RouteID, string S_StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetRouteCheck", ReplyAction="http://tempuri.org/IPartSelectSVC/GetRouteCheckResponse")]
        string GetRouteCheck(int Scan_StationTypeID, int Scan_StationID, string LineID, System.Data.DataTable DT_Unit, string S_Str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetRouteCheck", ReplyAction="http://tempuri.org/IPartSelectSVC/GetRouteCheckResponse")]
        System.Threading.Tasks.Task<string> GetRouteCheckAsync(int Scan_StationTypeID, int Scan_StationID, string LineID, System.Data.DataTable DT_Unit, string S_Str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_UnitID", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_UnitIDResponse")]
        System.Data.DataSet Get_UnitID(string S_SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_UnitID", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_UnitIDResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_UnitIDAsync(string S_SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_CreateMesSN", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_CreateMesSNResponse")]
        App.MyMES.PartSelectService.Get_CreateMesSNResponse Get_CreateMesSN(App.MyMES.PartSelectService.Get_CreateMesSNRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_CreateMesSN", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_CreateMesSNResponse")]
        System.Threading.Tasks.Task<App.MyMES.PartSelectService.Get_CreateMesSNResponse> Get_CreateMesSNAsync(App.MyMES.PartSelectService.Get_CreateMesSNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/BoxSnToBatch", ReplyAction="http://tempuri.org/IPartSelectSVC/BoxSnToBatchResponse")]
        App.MyMES.PartSelectService.BoxSnToBatchResponse BoxSnToBatch(App.MyMES.PartSelectService.BoxSnToBatchRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/BoxSnToBatch", ReplyAction="http://tempuri.org/IPartSelectSVC/BoxSnToBatchResponse")]
        System.Threading.Tasks.Task<App.MyMES.PartSelectService.BoxSnToBatchResponse> BoxSnToBatchAsync(App.MyMES.PartSelectService.BoxSnToBatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetComponentCount", ReplyAction="http://tempuri.org/IPartSelectSVC/GetComponentCountResponse")]
        int GetComponentCount(string ParentPartID, string StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetComponentCount", ReplyAction="http://tempuri.org/IPartSelectSVC/GetComponentCountResponse")]
        System.Threading.Tasks.Task<int> GetComponentCountAsync(string ParentPartID, string StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesUnitComponent", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesUnitComponentResponse")]
        System.Data.DataSet GetmesUnitComponent(string UnitID, string ChildUnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesUnitComponent", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesUnitComponentResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesUnitComponentAsync(string UnitID, string ChildUnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesProductStructure", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesProductStructureResponse")]
        System.Data.DataSet GetmesProductStructure(string ParentPartID, string PartID, string StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesProductStructure", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesProductStructureResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesProductStructureAsync(string ParentPartID, string PartID, string StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesProductStructure1", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesProductStructure1Response")]
        System.Data.DataSet GetmesProductStructure1(string ParentPartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesProductStructure1", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesProductStructure1Response")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesProductStructure1Async(string ParentPartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesProductStructure2", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesProductStructure2Response")]
        System.Data.DataSet GetmesProductStructure2(string ParentPartID, string StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesProductStructure2", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesProductStructure2Response")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesProductStructure2Async(string ParentPartID, string StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetChildScanLast", ReplyAction="http://tempuri.org/IPartSelectSVC/GetChildScanLastResponse")]
        System.Data.DataSet GetChildScanLast(string S_SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetChildScanLast", ReplyAction="http://tempuri.org/IPartSelectSVC/GetChildScanLastResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetChildScanLastAsync(string S_SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/ModPO", ReplyAction="http://tempuri.org/IPartSelectSVC/ModPOResponse")]
        void ModPO(string S_POID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/ModPO", ReplyAction="http://tempuri.org/IPartSelectSVC/ModPOResponse")]
        System.Threading.Tasks.Task ModPOAsync(string S_POID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/ModMachine", ReplyAction="http://tempuri.org/IPartSelectSVC/ModMachineResponse")]
        void ModMachine(string S_SN, string StatusID, bool IsUpUnitDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/ModMachine", ReplyAction="http://tempuri.org/IPartSelectSVC/ModMachineResponse")]
        System.Threading.Tasks.Task ModMachineAsync(string S_SN, string StatusID, bool IsUpUnitDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/ModMachine2", ReplyAction="http://tempuri.org/IPartSelectSVC/ModMachine2Response")]
        void ModMachine2(string ID, string StatusID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/ModMachine2", ReplyAction="http://tempuri.org/IPartSelectSVC/ModMachine2Response")]
        System.Threading.Tasks.Task ModMachine2Async(string ID, string StatusID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetProductionOrder", ReplyAction="http://tempuri.org/IPartSelectSVC/GetProductionOrderResponse")]
        System.Data.DataSet GetProductionOrder(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetProductionOrder", ReplyAction="http://tempuri.org/IPartSelectSVC/GetProductionOrderResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetProductionOrderAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetMesPackageStatusID", ReplyAction="http://tempuri.org/IPartSelectSVC/GetMesPackageStatusIDResponse")]
        System.Data.DataSet GetMesPackageStatusID(string PalletSN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetMesPackageStatusID", ReplyAction="http://tempuri.org/IPartSelectSVC/GetMesPackageStatusIDResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMesPackageStatusIDAsync(string PalletSN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesSerialNumber", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesSerialNumberResponse")]
        System.Data.DataSet GetmesSerialNumber(string S_SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesSerialNumber", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesSerialNumberResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesSerialNumberAsync(string S_SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesUnit", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesUnitResponse")]
        System.Data.DataSet GetmesUnit(string UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesUnit", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesUnitResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesUnitAsync(string UnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetComponent", ReplyAction="http://tempuri.org/IPartSelectSVC/GetComponentResponse")]
        System.Data.DataSet GetComponent(int I_ChildUnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetComponent", ReplyAction="http://tempuri.org/IPartSelectSVC/GetComponentResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetComponentAsync(int I_ChildUnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesMachine", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesMachineResponse")]
        System.Data.DataSet GetmesMachine(string S_SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesMachine", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesMachineResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesMachineAsync(string S_SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesRouteMachineMap", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesRouteMachineMapResponse")]
        System.Data.DataSet GetmesRouteMachineMap(string MachineID, string MachineFamilyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetmesRouteMachineMap", ReplyAction="http://tempuri.org/IPartSelectSVC/GetmesRouteMachineMapResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetmesRouteMachineMapAsync(string MachineID, string MachineFamilyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetSNParameter", ReplyAction="http://tempuri.org/IPartSelectSVC/GetSNParameterResponse")]
        System.Data.DataSet GetSNParameter(int PartID, int TemplateType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetSNParameter", ReplyAction="http://tempuri.org/IPartSelectSVC/GetSNParameterResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSNParameterAsync(int PartID, int TemplateType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetLBLGenLabel", ReplyAction="http://tempuri.org/IPartSelectSVC/GetLBLGenLabelResponse")]
        System.Data.DataSet GetLBLGenLabel(string S_SN, string S_LabelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetLBLGenLabel", ReplyAction="http://tempuri.org/IPartSelectSVC/GetLBLGenLabelResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLBLGenLabelAsync(string S_SN, string S_LabelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetLabelName", ReplyAction="http://tempuri.org/IPartSelectSVC/GetLabelNameResponse")]
        System.Data.DataSet GetLabelName(string StationTypeID, string PartFamilyID, string PartID, string ProductionOrderID, string LineID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetLabelName", ReplyAction="http://tempuri.org/IPartSelectSVC/GetLabelNameResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLabelNameAsync(string StationTypeID, string PartFamilyID, string PartID, string ProductionOrderID, string LineID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetPartParameter", ReplyAction="http://tempuri.org/IPartSelectSVC/GetPartParameterResponse")]
        System.Data.DataSet GetPartParameter(string PartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetPartParameter", ReplyAction="http://tempuri.org/IPartSelectSVC/GetPartParameterResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPartParameterAsync(string PartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluDefectType", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluDefectTypeResponse")]
        string GetluDefectType(string Description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetluDefectType", ReplyAction="http://tempuri.org/IPartSelectSVC/GetluDefectTypeResponse")]
        System.Threading.Tasks.Task<string> GetluDefectTypeAsync(string Description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/uspKitBoxCheck", ReplyAction="http://tempuri.org/IPartSelectSVC/uspKitBoxCheckResponse")]
        string uspKitBoxCheck(string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strSNbuf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/uspKitBoxCheck", ReplyAction="http://tempuri.org/IPartSelectSVC/uspKitBoxCheckResponse")]
        System.Threading.Tasks.Task<string> uspKitBoxCheckAsync(string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strSNbuf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/uspKitBoxPackaging", ReplyAction="http://tempuri.org/IPartSelectSVC/uspKitBoxPackagingResponse")]
        string uspKitBoxPackaging(string PartID, string ProductionOrderID, string S_UPCSN, string S_CartonSN, App.Model.LoginList LoginList, int BoxQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/uspKitBoxPackaging", ReplyAction="http://tempuri.org/IPartSelectSVC/uspKitBoxPackagingResponse")]
        System.Threading.Tasks.Task<string> uspKitBoxPackagingAsync(string PartID, string ProductionOrderID, string S_UPCSN, string S_CartonSN, App.Model.LoginList LoginList, int BoxQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/uspPalletCheck", ReplyAction="http://tempuri.org/IPartSelectSVC/uspPalletCheckResponse")]
        string uspPalletCheck(string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strSNbuf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/uspPalletCheck", ReplyAction="http://tempuri.org/IPartSelectSVC/uspPalletCheckResponse")]
        System.Threading.Tasks.Task<string> uspPalletCheckAsync(string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strSNbuf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/uspPalletPackaging", ReplyAction="http://tempuri.org/IPartSelectSVC/uspPalletPackagingResponse")]
        string uspPalletPackaging(string PartID, string ProductionOrderID, string S_CartonSN, string S_PalletSN, App.Model.LoginList loginList, int PalletQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/uspPalletPackaging", ReplyAction="http://tempuri.org/IPartSelectSVC/uspPalletPackagingResponse")]
        System.Threading.Tasks.Task<string> uspPalletPackagingAsync(string PartID, string ProductionOrderID, string S_CartonSN, string S_PalletSN, App.Model.LoginList loginList, int PalletQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetProductionOrderDetailDef", ReplyAction="http://tempuri.org/IPartSelectSVC/GetProductionOrderDetailDefResponse")]
        System.Data.DataSet GetProductionOrderDetailDef(string ProductionOrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/GetProductionOrderDetailDef", ReplyAction="http://tempuri.org/IPartSelectSVC/GetProductionOrderDetailDefResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetProductionOrderDetailDefAsync(string ProductionOrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_CreatePackageSN", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_CreatePackageSNResponse")]
        App.MyMES.PartSelectService.Get_CreatePackageSNResponse Get_CreatePackageSN(App.MyMES.PartSelectService.Get_CreatePackageSNRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_CreatePackageSN", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_CreatePackageSNResponse")]
        System.Threading.Tasks.Task<App.MyMES.PartSelectService.Get_CreatePackageSNResponse> Get_CreatePackageSNAsync(App.MyMES.PartSelectService.Get_CreatePackageSNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_PackageData", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_PackageDataResponse")]
        System.Data.DataSet Get_PackageData(string S_SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_PackageData", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_PackageDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_PackageDataAsync(string S_SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_PalletData", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_PalletDataResponse")]
        System.Data.DataSet Get_PalletData(string S_SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_PalletData", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_PalletDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_PalletDataAsync(string S_SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_SearchData", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_SearchDataResponse")]
        App.MyMES.PartSelectService.Get_SearchDataResponse Get_SearchData(App.MyMES.PartSelectService.Get_SearchDataRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_SearchData", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_SearchDataResponse")]
        System.Threading.Tasks.Task<App.MyMES.PartSelectService.Get_SearchDataResponse> Get_SearchDataAsync(App.MyMES.PartSelectService.Get_SearchDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/uspCallProcedure", ReplyAction="http://tempuri.org/IPartSelectSVC/uspCallProcedureResponse")]
        App.MyMES.PartSelectService.uspCallProcedureResponse uspCallProcedure(App.MyMES.PartSelectService.uspCallProcedureRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/uspCallProcedure", ReplyAction="http://tempuri.org/IPartSelectSVC/uspCallProcedureResponse")]
        System.Threading.Tasks.Task<App.MyMES.PartSelectService.uspCallProcedureResponse> uspCallProcedureAsync(App.MyMES.PartSelectService.uspCallProcedureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_PartParameter", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_PartParameterResponse")]
        System.Data.DataSet Get_PartParameter(string PartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/Get_PartParameter", ReplyAction="http://tempuri.org/IPartSelectSVC/Get_PartParameterResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_PartParameterAsync(string PartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/MESGetBomPartInfo", ReplyAction="http://tempuri.org/IPartSelectSVC/MESGetBomPartInfoResponse")]
        System.Data.DataSet MESGetBomPartInfo(int ParentPartID, int StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/MESGetBomPartInfo", ReplyAction="http://tempuri.org/IPartSelectSVC/MESGetBomPartInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> MESGetBomPartInfoAsync(int ParentPartID, int StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/MESAssembleCheckMianSN", ReplyAction="http://tempuri.org/IPartSelectSVC/MESAssembleCheckMianSNResponse")]
        string MESAssembleCheckMianSN(string ProductionOrderID, int LineID, int StationID, int StationTypeID, string SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/MESAssembleCheckMianSN", ReplyAction="http://tempuri.org/IPartSelectSVC/MESAssembleCheckMianSNResponse")]
        System.Threading.Tasks.Task<string> MESAssembleCheckMianSNAsync(string ProductionOrderID, int LineID, int StationID, int StationTypeID, string SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/MESAssembleCheckOtherSN", ReplyAction="http://tempuri.org/IPartSelectSVC/MESAssembleCheckOtherSNResponse")]
        string MESAssembleCheckOtherSN(string SN, string PartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/MESAssembleCheckOtherSN", ReplyAction="http://tempuri.org/IPartSelectSVC/MESAssembleCheckOtherSNResponse")]
        System.Threading.Tasks.Task<string> MESAssembleCheckOtherSNAsync(string SN, string PartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/MESAssembleCheckVirtualSN", ReplyAction="http://tempuri.org/IPartSelectSVC/MESAssembleCheckVirtualSNResponse")]
        string MESAssembleCheckVirtualSN(string SN, string PartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/MESAssembleCheckVirtualSN", ReplyAction="http://tempuri.org/IPartSelectSVC/MESAssembleCheckVirtualSNResponse")]
        System.Threading.Tasks.Task<string> MESAssembleCheckVirtualSNAsync(string SN, string PartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/MESModifyUnitDetail", ReplyAction="http://tempuri.org/IPartSelectSVC/MESModifyUnitDetailResponse")]
        void MESModifyUnitDetail(int UnitID, string FileName, string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartSelectSVC/MESModifyUnitDetail", ReplyAction="http://tempuri.org/IPartSelectSVC/MESModifyUnitDetailResponse")]
        System.Threading.Tasks.Task MESModifyUnitDetailAsync(int UnitID, string FileName, string Value);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_CreateMesSN", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_CreateMesSNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strSNFormat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string xmlProdOrder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string xmlPart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string xmlStation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string xmlExtraData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public App.Model.mesUnit v_mesUnit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public System.Data.DataSet dsSN;
        
        public Get_CreateMesSNRequest() {
        }
        
        public Get_CreateMesSNRequest(string strSNFormat, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, App.Model.mesUnit v_mesUnit, int number, System.Data.DataSet dsSN) {
            this.strSNFormat = strSNFormat;
            this.xmlProdOrder = xmlProdOrder;
            this.xmlPart = xmlPart;
            this.xmlStation = xmlStation;
            this.xmlExtraData = xmlExtraData;
            this.v_mesUnit = v_mesUnit;
            this.number = number;
            this.dsSN = dsSN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_CreateMesSNResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_CreateMesSNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Get_CreateMesSNResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataSet dsSN;
        
        public Get_CreateMesSNResponse() {
        }
        
        public Get_CreateMesSNResponse(string Get_CreateMesSNResult, System.Data.DataSet dsSN) {
            this.Get_CreateMesSNResult = Get_CreateMesSNResult;
            this.dsSN = dsSN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BoxSnToBatch", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BoxSnToBatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string S_BoxSN;
        
        public BoxSnToBatchRequest() {
        }
        
        public BoxSnToBatchRequest(string S_BoxSN) {
            this.S_BoxSN = S_BoxSN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BoxSnToBatchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BoxSnToBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet BoxSnToBatchResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string S_Result;
        
        public BoxSnToBatchResponse() {
        }
        
        public BoxSnToBatchResponse(System.Data.DataSet BoxSnToBatchResult, string S_Result) {
            this.BoxSnToBatchResult = BoxSnToBatchResult;
            this.S_Result = S_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_CreatePackageSN", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_CreatePackageSNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string S_FormatName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string xmlProdOrder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string xmlPart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string xmlStation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string xmlExtraData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public App.Model.mesUnit v_mesUnit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strSN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int type;
        
        public Get_CreatePackageSNRequest() {
        }
        
        public Get_CreatePackageSNRequest(string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, App.Model.mesUnit v_mesUnit, string strSN, int type) {
            this.S_FormatName = S_FormatName;
            this.xmlProdOrder = xmlProdOrder;
            this.xmlPart = xmlPart;
            this.xmlStation = xmlStation;
            this.xmlExtraData = xmlExtraData;
            this.v_mesUnit = v_mesUnit;
            this.strSN = strSN;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_CreatePackageSNResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_CreatePackageSNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Get_CreatePackageSNResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strSN;
        
        public Get_CreatePackageSNResponse() {
        }
        
        public Get_CreatePackageSNResponse(string Get_CreatePackageSNResult, string strSN) {
            this.Get_CreatePackageSNResult = Get_CreatePackageSNResult;
            this.strSN = strSN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_SearchData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_SearchDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string S_FormatName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string xmlProdOrder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string xmlPart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string xmlStation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string xmlExtraData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strSNbuf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strOutput;
        
        public Get_SearchDataRequest() {
        }
        
        public Get_SearchDataRequest(string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strSNbuf, string strOutput) {
            this.S_FormatName = S_FormatName;
            this.xmlProdOrder = xmlProdOrder;
            this.xmlPart = xmlPart;
            this.xmlStation = xmlStation;
            this.xmlExtraData = xmlExtraData;
            this.strSNbuf = strSNbuf;
            this.strOutput = strOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_SearchDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_SearchDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet Get_SearchDataResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strOutput;
        
        public Get_SearchDataResponse() {
        }
        
        public Get_SearchDataResponse(System.Data.DataSet Get_SearchDataResult, string strOutput) {
            this.Get_SearchDataResult = Get_SearchDataResult;
            this.strOutput = strOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uspCallProcedure", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class uspCallProcedureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Pro_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string S_FormatName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string xmlProdOrder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string xmlPart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string xmlStation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string xmlExtraData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strSNbuf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string strOutput;
        
        public uspCallProcedureRequest() {
        }
        
        public uspCallProcedureRequest(string Pro_Name, string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strSNbuf, string strOutput) {
            this.Pro_Name = Pro_Name;
            this.S_FormatName = S_FormatName;
            this.xmlProdOrder = xmlProdOrder;
            this.xmlPart = xmlPart;
            this.xmlStation = xmlStation;
            this.xmlExtraData = xmlExtraData;
            this.strSNbuf = strSNbuf;
            this.strOutput = strOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uspCallProcedureResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class uspCallProcedureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet uspCallProcedureResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strOutput;
        
        public uspCallProcedureResponse() {
        }
        
        public uspCallProcedureResponse(System.Data.DataSet uspCallProcedureResult, string strOutput) {
            this.uspCallProcedureResult = uspCallProcedureResult;
            this.strOutput = strOutput;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartSelectSVCChannel : App.MyMES.PartSelectService.IPartSelectSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartSelectSVCClient : System.ServiceModel.ClientBase<App.MyMES.PartSelectService.IPartSelectSVC>, App.MyMES.PartSelectService.IPartSelectSVC {
        
        public PartSelectSVCClient() {
        }
        
        public PartSelectSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartSelectSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartSelectSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartSelectSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double MyTest() {
            return base.Channel.MyTest();
        }
        
        public System.Threading.Tasks.Task<double> MyTestAsync() {
            return base.Channel.MyTestAsync();
        }
        
        public System.Data.DataSet P_DataSet(string S_Sql) {
            return base.Channel.P_DataSet(S_Sql);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> P_DataSetAsync(string S_Sql) {
            return base.Channel.P_DataSetAsync(S_Sql);
        }
        
        public string ExecSql(string S_Sql) {
            return base.Channel.ExecSql(S_Sql);
        }
        
        public System.Threading.Tasks.Task<string> ExecSqlAsync(string S_Sql) {
            return base.Channel.ExecSqlAsync(S_Sql);
        }
        
        public System.Data.DataSet GetluPartFamilyType() {
            return base.Channel.GetluPartFamilyType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetluPartFamilyTypeAsync() {
            return base.Channel.GetluPartFamilyTypeAsync();
        }
        
        public string GetServerIP() {
            return base.Channel.GetServerIP();
        }
        
        public System.Threading.Tasks.Task<string> GetServerIPAsync() {
            return base.Channel.GetServerIPAsync();
        }
        
        public System.Data.DataSet GetluPartFamily(string PartFamilyTypeID) {
            return base.Channel.GetluPartFamily(PartFamilyTypeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetluPartFamilyAsync(string PartFamilyTypeID) {
            return base.Channel.GetluPartFamilyAsync(PartFamilyTypeID);
        }
        
        public System.Data.DataSet GetmesPart(string PartFamilyID) {
            return base.Channel.GetmesPart(PartFamilyID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesPartAsync(string PartFamilyID) {
            return base.Channel.GetmesPartAsync(PartFamilyID);
        }
        
        public System.Data.DataSet GetmesPartDetail(int PartID, string PartDetailDefName) {
            return base.Channel.GetmesPartDetail(PartID, PartDetailDefName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesPartDetailAsync(int PartID, string PartDetailDefName) {
            return base.Channel.GetmesPartDetailAsync(PartID, PartDetailDefName);
        }
        
        public System.Data.DataSet GetluPODetailDef(int ProductionOrderID, string PODetailDef) {
            return base.Channel.GetluPODetailDef(ProductionOrderID, PODetailDef);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetluPODetailDefAsync(int ProductionOrderID, string PODetailDef) {
            return base.Channel.GetluPODetailDefAsync(ProductionOrderID, PODetailDef);
        }
        
        public System.Data.DataSet GetmesPartPrint() {
            return base.Channel.GetmesPartPrint();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesPartPrintAsync() {
            return base.Channel.GetmesPartPrintAsync();
        }
        
        public System.Data.DataSet GetmesLine() {
            return base.Channel.GetmesLine();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesLineAsync() {
            return base.Channel.GetmesLineAsync();
        }
        
        public System.Data.DataSet mesLineGroup(string LineType, int PartFamilyTypeID) {
            return base.Channel.mesLineGroup(LineType, PartFamilyTypeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mesLineGroupAsync(string LineType, int PartFamilyTypeID) {
            return base.Channel.mesLineGroupAsync(LineType, PartFamilyTypeID);
        }
        
        public System.Data.DataSet GetsysStatus() {
            return base.Channel.GetsysStatus();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetsysStatusAsync() {
            return base.Channel.GetsysStatusAsync();
        }
        
        public System.Data.DataSet GetmesStationType() {
            return base.Channel.GetmesStationType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesStationTypeAsync() {
            return base.Channel.GetmesStationTypeAsync();
        }
        
        public System.Data.DataSet GetmesRoute() {
            return base.Channel.GetmesRoute();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesRouteAsync() {
            return base.Channel.GetmesRouteAsync();
        }
        
        public System.Data.DataSet GetRouteSequence(string RouteID, string StationTypeID) {
            return base.Channel.GetRouteSequence(RouteID, StationTypeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetRouteSequenceAsync(string RouteID, string StationTypeID) {
            return base.Channel.GetRouteSequenceAsync(RouteID, StationTypeID);
        }
        
        public System.Data.DataSet GetmesStation(string LineID) {
            return base.Channel.GetmesStation(LineID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesStationAsync(string LineID) {
            return base.Channel.GetmesStationAsync(LineID);
        }
        
        public System.Data.DataSet GetmesStationTypeByStationID(string StationID) {
            return base.Channel.GetmesStationTypeByStationID(StationID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesStationTypeByStationIDAsync(string StationID) {
            return base.Channel.GetmesStationTypeByStationIDAsync(StationID);
        }
        
        public System.Data.DataSet GetluSerialNumberType() {
            return base.Channel.GetluSerialNumberType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetluSerialNumberTypeAsync() {
            return base.Channel.GetluSerialNumberTypeAsync();
        }
        
        public System.Data.DataSet GetUnit(string PartID) {
            return base.Channel.GetUnit(PartID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUnitAsync(string PartID) {
            return base.Channel.GetUnitAsync(PartID);
        }
        
        public System.Data.DataSet GetUnit2(string PartID, string StationID, string POID) {
            return base.Channel.GetUnit2(PartID, StationID, POID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUnit2Async(string PartID, string StationID, string POID) {
            return base.Channel.GetUnit2Async(PartID, StationID, POID);
        }
        
        public System.Data.DataSet GetMachineHistory(string S_UnitID) {
            return base.Channel.GetMachineHistory(S_UnitID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMachineHistoryAsync(string S_UnitID) {
            return base.Channel.GetMachineHistoryAsync(S_UnitID);
        }
        
        public System.Data.DataSet GetUnit_Search(string S_DateStart, string S_DateEnd, string S_Where) {
            return base.Channel.GetUnit_Search(S_DateStart, S_DateEnd, S_Where);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUnit_SearchAsync(string S_DateStart, string S_DateEnd, string S_Where) {
            return base.Channel.GetUnit_SearchAsync(S_DateStart, S_DateEnd, S_Where);
        }
        
        public System.Data.DataSet GetUnitComponent(string S_UnitID) {
            return base.Channel.GetUnitComponent(S_UnitID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUnitComponentAsync(string S_UnitID) {
            return base.Channel.GetUnitComponentAsync(S_UnitID);
        }
        
        public System.Data.DataSet GetmesUnitDetail(string S_UnitID) {
            return base.Channel.GetmesUnitDetail(S_UnitID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesUnitDetailAsync(string S_UnitID) {
            return base.Channel.GetmesUnitDetailAsync(S_UnitID);
        }
        
        public System.Data.DataSet GetHistory(string UnitID) {
            return base.Channel.GetHistory(UnitID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetHistoryAsync(string UnitID) {
            return base.Channel.GetHistoryAsync(UnitID);
        }
        
        public System.Data.DataSet GetmesUnitState(string S_PartID, string S_RouteSequence, string LineID, int StationTypeID) {
            return base.Channel.GetmesUnitState(S_PartID, S_RouteSequence, LineID, StationTypeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesUnitStateAsync(string S_PartID, string S_RouteSequence, string LineID, int StationTypeID) {
            return base.Channel.GetmesUnitStateAsync(S_PartID, S_RouteSequence, LineID, StationTypeID);
        }
        
        public System.Data.DataSet GetmesSerialNumberOfLine(string SNCategory, string PrintCount) {
            return base.Channel.GetmesSerialNumberOfLine(SNCategory, PrintCount);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesSerialNumberOfLineAsync(string SNCategory, string PrintCount) {
            return base.Channel.GetmesSerialNumberOfLineAsync(SNCategory, PrintCount);
        }
        
        public System.Data.DataSet GetmesSerialNumberByUnitID(string UnitID) {
            return base.Channel.GetmesSerialNumberByUnitID(UnitID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesSerialNumberByUnitIDAsync(string UnitID) {
            return base.Channel.GetmesSerialNumberByUnitIDAsync(UnitID);
        }
        
        public System.Data.DataSet GetPO(string S_PartID, string S_StatusID) {
            return base.Channel.GetPO(S_PartID, S_StatusID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPOAsync(string S_PartID, string S_StatusID) {
            return base.Channel.GetPOAsync(S_PartID, S_StatusID);
        }
        
        public System.Data.DataSet GetPOAll(string S_PartID, string S_LineID) {
            return base.Channel.GetPOAll(S_PartID, S_LineID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPOAllAsync(string S_PartID, string S_LineID) {
            return base.Channel.GetPOAllAsync(S_PartID, S_LineID);
        }
        
        public System.Data.DataSet GetRoute(string PartID, string S_RouteSequence, string LineID, int StationTypeID) {
            return base.Channel.GetRoute(PartID, S_RouteSequence, LineID, StationTypeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetRouteAsync(string PartID, string S_RouteSequence, string LineID, int StationTypeID) {
            return base.Channel.GetRouteAsync(PartID, S_RouteSequence, LineID, StationTypeID);
        }
        
        public System.Data.DataSet GetApplicationType(string StationTypeID) {
            return base.Channel.GetApplicationType(StationTypeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetApplicationTypeAsync(string StationTypeID) {
            return base.Channel.GetApplicationTypeAsync(StationTypeID);
        }
        
        public System.Data.DataSet GetluDefect(int DefectTypeID) {
            return base.Channel.GetluDefect(DefectTypeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetluDefectAsync(int DefectTypeID) {
            return base.Channel.GetluDefectAsync(DefectTypeID);
        }
        
        public System.Data.DataSet GetluUnitStatus() {
            return base.Channel.GetluUnitStatus();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetluUnitStatusAsync() {
            return base.Channel.GetluUnitStatusAsync();
        }
        
        public System.Data.DataSet GetmesUnitDefect(string S_UnitID) {
            return base.Channel.GetmesUnitDefect(S_UnitID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesUnitDefectAsync(string S_UnitID) {
            return base.Channel.GetmesUnitDefectAsync(S_UnitID);
        }
        
        public System.Data.DataSet uspSNRGetNext(string strSNFormat, int ReuseSNByStation, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strNextSN) {
            return base.Channel.uspSNRGetNext(strSNFormat, ReuseSNByStation, xmlProdOrder, xmlPart, xmlStation, xmlExtraData, strNextSN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> uspSNRGetNextAsync(string strSNFormat, int ReuseSNByStation, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strNextSN) {
            return base.Channel.uspSNRGetNextAsync(strSNFormat, ReuseSNByStation, xmlProdOrder, xmlPart, xmlStation, xmlExtraData, strNextSN);
        }
        
        public System.Data.DataSet GetPartDetailDef(string SN) {
            return base.Channel.GetPartDetailDef(SN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPartDetailDefAsync(string SN) {
            return base.Channel.GetPartDetailDefAsync(SN);
        }
        
        public string Get_MachineRouteMap(string S_ToolSN, string S_ProductPartID, string S_RouteID, string S_StationTypeID) {
            return base.Channel.Get_MachineRouteMap(S_ToolSN, S_ProductPartID, S_RouteID, S_StationTypeID);
        }
        
        public System.Threading.Tasks.Task<string> Get_MachineRouteMapAsync(string S_ToolSN, string S_ProductPartID, string S_RouteID, string S_StationTypeID) {
            return base.Channel.Get_MachineRouteMapAsync(S_ToolSN, S_ProductPartID, S_RouteID, S_StationTypeID);
        }
        
        public string GetRouteCheck(int Scan_StationTypeID, int Scan_StationID, string LineID, System.Data.DataTable DT_Unit, string S_Str) {
            return base.Channel.GetRouteCheck(Scan_StationTypeID, Scan_StationID, LineID, DT_Unit, S_Str);
        }
        
        public System.Threading.Tasks.Task<string> GetRouteCheckAsync(int Scan_StationTypeID, int Scan_StationID, string LineID, System.Data.DataTable DT_Unit, string S_Str) {
            return base.Channel.GetRouteCheckAsync(Scan_StationTypeID, Scan_StationID, LineID, DT_Unit, S_Str);
        }
        
        public System.Data.DataSet Get_UnitID(string S_SN) {
            return base.Channel.Get_UnitID(S_SN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_UnitIDAsync(string S_SN) {
            return base.Channel.Get_UnitIDAsync(S_SN);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.MyMES.PartSelectService.Get_CreateMesSNResponse App.MyMES.PartSelectService.IPartSelectSVC.Get_CreateMesSN(App.MyMES.PartSelectService.Get_CreateMesSNRequest request) {
            return base.Channel.Get_CreateMesSN(request);
        }
        
        public string Get_CreateMesSN(string strSNFormat, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, App.Model.mesUnit v_mesUnit, int number, ref System.Data.DataSet dsSN) {
            App.MyMES.PartSelectService.Get_CreateMesSNRequest inValue = new App.MyMES.PartSelectService.Get_CreateMesSNRequest();
            inValue.strSNFormat = strSNFormat;
            inValue.xmlProdOrder = xmlProdOrder;
            inValue.xmlPart = xmlPart;
            inValue.xmlStation = xmlStation;
            inValue.xmlExtraData = xmlExtraData;
            inValue.v_mesUnit = v_mesUnit;
            inValue.number = number;
            inValue.dsSN = dsSN;
            App.MyMES.PartSelectService.Get_CreateMesSNResponse retVal = ((App.MyMES.PartSelectService.IPartSelectSVC)(this)).Get_CreateMesSN(inValue);
            dsSN = retVal.dsSN;
            return retVal.Get_CreateMesSNResult;
        }
        
        public System.Threading.Tasks.Task<App.MyMES.PartSelectService.Get_CreateMesSNResponse> Get_CreateMesSNAsync(App.MyMES.PartSelectService.Get_CreateMesSNRequest request) {
            return base.Channel.Get_CreateMesSNAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.MyMES.PartSelectService.BoxSnToBatchResponse App.MyMES.PartSelectService.IPartSelectSVC.BoxSnToBatch(App.MyMES.PartSelectService.BoxSnToBatchRequest request) {
            return base.Channel.BoxSnToBatch(request);
        }
        
        public System.Data.DataSet BoxSnToBatch(string S_BoxSN, out string S_Result) {
            App.MyMES.PartSelectService.BoxSnToBatchRequest inValue = new App.MyMES.PartSelectService.BoxSnToBatchRequest();
            inValue.S_BoxSN = S_BoxSN;
            App.MyMES.PartSelectService.BoxSnToBatchResponse retVal = ((App.MyMES.PartSelectService.IPartSelectSVC)(this)).BoxSnToBatch(inValue);
            S_Result = retVal.S_Result;
            return retVal.BoxSnToBatchResult;
        }
        
        public System.Threading.Tasks.Task<App.MyMES.PartSelectService.BoxSnToBatchResponse> BoxSnToBatchAsync(App.MyMES.PartSelectService.BoxSnToBatchRequest request) {
            return base.Channel.BoxSnToBatchAsync(request);
        }
        
        public int GetComponentCount(string ParentPartID, string StationTypeID) {
            return base.Channel.GetComponentCount(ParentPartID, StationTypeID);
        }
        
        public System.Threading.Tasks.Task<int> GetComponentCountAsync(string ParentPartID, string StationTypeID) {
            return base.Channel.GetComponentCountAsync(ParentPartID, StationTypeID);
        }
        
        public System.Data.DataSet GetmesUnitComponent(string UnitID, string ChildUnitID) {
            return base.Channel.GetmesUnitComponent(UnitID, ChildUnitID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesUnitComponentAsync(string UnitID, string ChildUnitID) {
            return base.Channel.GetmesUnitComponentAsync(UnitID, ChildUnitID);
        }
        
        public System.Data.DataSet GetmesProductStructure(string ParentPartID, string PartID, string StationTypeID) {
            return base.Channel.GetmesProductStructure(ParentPartID, PartID, StationTypeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesProductStructureAsync(string ParentPartID, string PartID, string StationTypeID) {
            return base.Channel.GetmesProductStructureAsync(ParentPartID, PartID, StationTypeID);
        }
        
        public System.Data.DataSet GetmesProductStructure1(string ParentPartID) {
            return base.Channel.GetmesProductStructure1(ParentPartID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesProductStructure1Async(string ParentPartID) {
            return base.Channel.GetmesProductStructure1Async(ParentPartID);
        }
        
        public System.Data.DataSet GetmesProductStructure2(string ParentPartID, string StationTypeID) {
            return base.Channel.GetmesProductStructure2(ParentPartID, StationTypeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesProductStructure2Async(string ParentPartID, string StationTypeID) {
            return base.Channel.GetmesProductStructure2Async(ParentPartID, StationTypeID);
        }
        
        public System.Data.DataSet GetChildScanLast(string S_SN) {
            return base.Channel.GetChildScanLast(S_SN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetChildScanLastAsync(string S_SN) {
            return base.Channel.GetChildScanLastAsync(S_SN);
        }
        
        public void ModPO(string S_POID) {
            base.Channel.ModPO(S_POID);
        }
        
        public System.Threading.Tasks.Task ModPOAsync(string S_POID) {
            return base.Channel.ModPOAsync(S_POID);
        }
        
        public void ModMachine(string S_SN, string StatusID, bool IsUpUnitDetail) {
            base.Channel.ModMachine(S_SN, StatusID, IsUpUnitDetail);
        }
        
        public System.Threading.Tasks.Task ModMachineAsync(string S_SN, string StatusID, bool IsUpUnitDetail) {
            return base.Channel.ModMachineAsync(S_SN, StatusID, IsUpUnitDetail);
        }
        
        public void ModMachine2(string ID, string StatusID) {
            base.Channel.ModMachine2(ID, StatusID);
        }
        
        public System.Threading.Tasks.Task ModMachine2Async(string ID, string StatusID) {
            return base.Channel.ModMachine2Async(ID, StatusID);
        }
        
        public System.Data.DataSet GetProductionOrder(string ID) {
            return base.Channel.GetProductionOrder(ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetProductionOrderAsync(string ID) {
            return base.Channel.GetProductionOrderAsync(ID);
        }
        
        public System.Data.DataSet GetMesPackageStatusID(string PalletSN) {
            return base.Channel.GetMesPackageStatusID(PalletSN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMesPackageStatusIDAsync(string PalletSN) {
            return base.Channel.GetMesPackageStatusIDAsync(PalletSN);
        }
        
        public System.Data.DataSet GetmesSerialNumber(string S_SN) {
            return base.Channel.GetmesSerialNumber(S_SN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesSerialNumberAsync(string S_SN) {
            return base.Channel.GetmesSerialNumberAsync(S_SN);
        }
        
        public System.Data.DataSet GetmesUnit(string UnitID) {
            return base.Channel.GetmesUnit(UnitID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesUnitAsync(string UnitID) {
            return base.Channel.GetmesUnitAsync(UnitID);
        }
        
        public System.Data.DataSet GetComponent(int I_ChildUnitID) {
            return base.Channel.GetComponent(I_ChildUnitID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetComponentAsync(int I_ChildUnitID) {
            return base.Channel.GetComponentAsync(I_ChildUnitID);
        }
        
        public System.Data.DataSet GetmesMachine(string S_SN) {
            return base.Channel.GetmesMachine(S_SN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesMachineAsync(string S_SN) {
            return base.Channel.GetmesMachineAsync(S_SN);
        }
        
        public System.Data.DataSet GetmesRouteMachineMap(string MachineID, string MachineFamilyID) {
            return base.Channel.GetmesRouteMachineMap(MachineID, MachineFamilyID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetmesRouteMachineMapAsync(string MachineID, string MachineFamilyID) {
            return base.Channel.GetmesRouteMachineMapAsync(MachineID, MachineFamilyID);
        }
        
        public System.Data.DataSet GetSNParameter(int PartID, int TemplateType) {
            return base.Channel.GetSNParameter(PartID, TemplateType);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSNParameterAsync(int PartID, int TemplateType) {
            return base.Channel.GetSNParameterAsync(PartID, TemplateType);
        }
        
        public System.Data.DataSet GetLBLGenLabel(string S_SN, string S_LabelName) {
            return base.Channel.GetLBLGenLabel(S_SN, S_LabelName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLBLGenLabelAsync(string S_SN, string S_LabelName) {
            return base.Channel.GetLBLGenLabelAsync(S_SN, S_LabelName);
        }
        
        public System.Data.DataSet GetLabelName(string StationTypeID, string PartFamilyID, string PartID, string ProductionOrderID, string LineID) {
            return base.Channel.GetLabelName(StationTypeID, PartFamilyID, PartID, ProductionOrderID, LineID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLabelNameAsync(string StationTypeID, string PartFamilyID, string PartID, string ProductionOrderID, string LineID) {
            return base.Channel.GetLabelNameAsync(StationTypeID, PartFamilyID, PartID, ProductionOrderID, LineID);
        }
        
        public System.Data.DataSet GetPartParameter(string PartID) {
            return base.Channel.GetPartParameter(PartID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPartParameterAsync(string PartID) {
            return base.Channel.GetPartParameterAsync(PartID);
        }
        
        public string GetluDefectType(string Description) {
            return base.Channel.GetluDefectType(Description);
        }
        
        public System.Threading.Tasks.Task<string> GetluDefectTypeAsync(string Description) {
            return base.Channel.GetluDefectTypeAsync(Description);
        }
        
        public string uspKitBoxCheck(string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strSNbuf) {
            return base.Channel.uspKitBoxCheck(S_FormatName, xmlProdOrder, xmlPart, xmlStation, xmlExtraData, strSNbuf);
        }
        
        public System.Threading.Tasks.Task<string> uspKitBoxCheckAsync(string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strSNbuf) {
            return base.Channel.uspKitBoxCheckAsync(S_FormatName, xmlProdOrder, xmlPart, xmlStation, xmlExtraData, strSNbuf);
        }
        
        public string uspKitBoxPackaging(string PartID, string ProductionOrderID, string S_UPCSN, string S_CartonSN, App.Model.LoginList LoginList, int BoxQty) {
            return base.Channel.uspKitBoxPackaging(PartID, ProductionOrderID, S_UPCSN, S_CartonSN, LoginList, BoxQty);
        }
        
        public System.Threading.Tasks.Task<string> uspKitBoxPackagingAsync(string PartID, string ProductionOrderID, string S_UPCSN, string S_CartonSN, App.Model.LoginList LoginList, int BoxQty) {
            return base.Channel.uspKitBoxPackagingAsync(PartID, ProductionOrderID, S_UPCSN, S_CartonSN, LoginList, BoxQty);
        }
        
        public string uspPalletCheck(string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strSNbuf) {
            return base.Channel.uspPalletCheck(S_FormatName, xmlProdOrder, xmlPart, xmlStation, xmlExtraData, strSNbuf);
        }
        
        public System.Threading.Tasks.Task<string> uspPalletCheckAsync(string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strSNbuf) {
            return base.Channel.uspPalletCheckAsync(S_FormatName, xmlProdOrder, xmlPart, xmlStation, xmlExtraData, strSNbuf);
        }
        
        public string uspPalletPackaging(string PartID, string ProductionOrderID, string S_CartonSN, string S_PalletSN, App.Model.LoginList loginList, int PalletQty) {
            return base.Channel.uspPalletPackaging(PartID, ProductionOrderID, S_CartonSN, S_PalletSN, loginList, PalletQty);
        }
        
        public System.Threading.Tasks.Task<string> uspPalletPackagingAsync(string PartID, string ProductionOrderID, string S_CartonSN, string S_PalletSN, App.Model.LoginList loginList, int PalletQty) {
            return base.Channel.uspPalletPackagingAsync(PartID, ProductionOrderID, S_CartonSN, S_PalletSN, loginList, PalletQty);
        }
        
        public System.Data.DataSet GetProductionOrderDetailDef(string ProductionOrderNumber) {
            return base.Channel.GetProductionOrderDetailDef(ProductionOrderNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetProductionOrderDetailDefAsync(string ProductionOrderNumber) {
            return base.Channel.GetProductionOrderDetailDefAsync(ProductionOrderNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.MyMES.PartSelectService.Get_CreatePackageSNResponse App.MyMES.PartSelectService.IPartSelectSVC.Get_CreatePackageSN(App.MyMES.PartSelectService.Get_CreatePackageSNRequest request) {
            return base.Channel.Get_CreatePackageSN(request);
        }
        
        public string Get_CreatePackageSN(string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, App.Model.mesUnit v_mesUnit, ref string strSN, int type) {
            App.MyMES.PartSelectService.Get_CreatePackageSNRequest inValue = new App.MyMES.PartSelectService.Get_CreatePackageSNRequest();
            inValue.S_FormatName = S_FormatName;
            inValue.xmlProdOrder = xmlProdOrder;
            inValue.xmlPart = xmlPart;
            inValue.xmlStation = xmlStation;
            inValue.xmlExtraData = xmlExtraData;
            inValue.v_mesUnit = v_mesUnit;
            inValue.strSN = strSN;
            inValue.type = type;
            App.MyMES.PartSelectService.Get_CreatePackageSNResponse retVal = ((App.MyMES.PartSelectService.IPartSelectSVC)(this)).Get_CreatePackageSN(inValue);
            strSN = retVal.strSN;
            return retVal.Get_CreatePackageSNResult;
        }
        
        public System.Threading.Tasks.Task<App.MyMES.PartSelectService.Get_CreatePackageSNResponse> Get_CreatePackageSNAsync(App.MyMES.PartSelectService.Get_CreatePackageSNRequest request) {
            return base.Channel.Get_CreatePackageSNAsync(request);
        }
        
        public System.Data.DataSet Get_PackageData(string S_SN) {
            return base.Channel.Get_PackageData(S_SN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_PackageDataAsync(string S_SN) {
            return base.Channel.Get_PackageDataAsync(S_SN);
        }
        
        public System.Data.DataSet Get_PalletData(string S_SN) {
            return base.Channel.Get_PalletData(S_SN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_PalletDataAsync(string S_SN) {
            return base.Channel.Get_PalletDataAsync(S_SN);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.MyMES.PartSelectService.Get_SearchDataResponse App.MyMES.PartSelectService.IPartSelectSVC.Get_SearchData(App.MyMES.PartSelectService.Get_SearchDataRequest request) {
            return base.Channel.Get_SearchData(request);
        }
        
        public System.Data.DataSet Get_SearchData(string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strSNbuf, ref string strOutput) {
            App.MyMES.PartSelectService.Get_SearchDataRequest inValue = new App.MyMES.PartSelectService.Get_SearchDataRequest();
            inValue.S_FormatName = S_FormatName;
            inValue.xmlProdOrder = xmlProdOrder;
            inValue.xmlPart = xmlPart;
            inValue.xmlStation = xmlStation;
            inValue.xmlExtraData = xmlExtraData;
            inValue.strSNbuf = strSNbuf;
            inValue.strOutput = strOutput;
            App.MyMES.PartSelectService.Get_SearchDataResponse retVal = ((App.MyMES.PartSelectService.IPartSelectSVC)(this)).Get_SearchData(inValue);
            strOutput = retVal.strOutput;
            return retVal.Get_SearchDataResult;
        }
        
        public System.Threading.Tasks.Task<App.MyMES.PartSelectService.Get_SearchDataResponse> Get_SearchDataAsync(App.MyMES.PartSelectService.Get_SearchDataRequest request) {
            return base.Channel.Get_SearchDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.MyMES.PartSelectService.uspCallProcedureResponse App.MyMES.PartSelectService.IPartSelectSVC.uspCallProcedure(App.MyMES.PartSelectService.uspCallProcedureRequest request) {
            return base.Channel.uspCallProcedure(request);
        }
        
        public System.Data.DataSet uspCallProcedure(string Pro_Name, string S_FormatName, string xmlProdOrder, string xmlPart, string xmlStation, string xmlExtraData, string strSNbuf, ref string strOutput) {
            App.MyMES.PartSelectService.uspCallProcedureRequest inValue = new App.MyMES.PartSelectService.uspCallProcedureRequest();
            inValue.Pro_Name = Pro_Name;
            inValue.S_FormatName = S_FormatName;
            inValue.xmlProdOrder = xmlProdOrder;
            inValue.xmlPart = xmlPart;
            inValue.xmlStation = xmlStation;
            inValue.xmlExtraData = xmlExtraData;
            inValue.strSNbuf = strSNbuf;
            inValue.strOutput = strOutput;
            App.MyMES.PartSelectService.uspCallProcedureResponse retVal = ((App.MyMES.PartSelectService.IPartSelectSVC)(this)).uspCallProcedure(inValue);
            strOutput = retVal.strOutput;
            return retVal.uspCallProcedureResult;
        }
        
        public System.Threading.Tasks.Task<App.MyMES.PartSelectService.uspCallProcedureResponse> uspCallProcedureAsync(App.MyMES.PartSelectService.uspCallProcedureRequest request) {
            return base.Channel.uspCallProcedureAsync(request);
        }
        
        public System.Data.DataSet Get_PartParameter(string PartID) {
            return base.Channel.Get_PartParameter(PartID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_PartParameterAsync(string PartID) {
            return base.Channel.Get_PartParameterAsync(PartID);
        }
        
        public System.Data.DataSet MESGetBomPartInfo(int ParentPartID, int StationTypeID) {
            return base.Channel.MESGetBomPartInfo(ParentPartID, StationTypeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MESGetBomPartInfoAsync(int ParentPartID, int StationTypeID) {
            return base.Channel.MESGetBomPartInfoAsync(ParentPartID, StationTypeID);
        }
        
        public string MESAssembleCheckMianSN(string ProductionOrderID, int LineID, int StationID, int StationTypeID, string SN) {
            return base.Channel.MESAssembleCheckMianSN(ProductionOrderID, LineID, StationID, StationTypeID, SN);
        }
        
        public System.Threading.Tasks.Task<string> MESAssembleCheckMianSNAsync(string ProductionOrderID, int LineID, int StationID, int StationTypeID, string SN) {
            return base.Channel.MESAssembleCheckMianSNAsync(ProductionOrderID, LineID, StationID, StationTypeID, SN);
        }
        
        public string MESAssembleCheckOtherSN(string SN, string PartID) {
            return base.Channel.MESAssembleCheckOtherSN(SN, PartID);
        }
        
        public System.Threading.Tasks.Task<string> MESAssembleCheckOtherSNAsync(string SN, string PartID) {
            return base.Channel.MESAssembleCheckOtherSNAsync(SN, PartID);
        }
        
        public string MESAssembleCheckVirtualSN(string SN, string PartID) {
            return base.Channel.MESAssembleCheckVirtualSN(SN, PartID);
        }
        
        public System.Threading.Tasks.Task<string> MESAssembleCheckVirtualSNAsync(string SN, string PartID) {
            return base.Channel.MESAssembleCheckVirtualSNAsync(SN, PartID);
        }
        
        public void MESModifyUnitDetail(int UnitID, string FileName, string Value) {
            base.Channel.MESModifyUnitDetail(UnitID, FileName, Value);
        }
        
        public System.Threading.Tasks.Task MESModifyUnitDetailAsync(int UnitID, string FileName, string Value) {
            return base.Channel.MESModifyUnitDetailAsync(UnitID, FileName, Value);
        }
    }
}
