//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.sysStatusService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="sysStatusService.IsysStatusSVC")]
    public interface IsysStatusSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsysStatusSVC/Insert", ReplyAction="http://tempuri.org/IsysStatusSVC/InsertResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.sysStatus[]))]
        int Insert(App.Model.sysStatus model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsysStatusSVC/Insert", ReplyAction="http://tempuri.org/IsysStatusSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.sysStatus model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsysStatusSVC/Delete", ReplyAction="http://tempuri.org/IsysStatusSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsysStatusSVC/Delete", ReplyAction="http://tempuri.org/IsysStatusSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsysStatusSVC/Update", ReplyAction="http://tempuri.org/IsysStatusSVC/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.sysStatus[]))]
        bool Update(App.Model.sysStatus model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsysStatusSVC/Update", ReplyAction="http://tempuri.org/IsysStatusSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.sysStatus model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsysStatusSVC/Get", ReplyAction="http://tempuri.org/IsysStatusSVC/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.sysStatus[]))]
        App.Model.sysStatus Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsysStatusSVC/Get", ReplyAction="http://tempuri.org/IsysStatusSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.sysStatus> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsysStatusSVC/ListAll", ReplyAction="http://tempuri.org/IsysStatusSVC/ListAllResponse")]
        App.Model.sysStatus[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsysStatusSVC/ListAll", ReplyAction="http://tempuri.org/IsysStatusSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.sysStatus[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsysStatusSVCChannel : App.MyMES.sysStatusService.IsysStatusSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsysStatusSVCClient : System.ServiceModel.ClientBase<App.MyMES.sysStatusService.IsysStatusSVC>, App.MyMES.sysStatusService.IsysStatusSVC {
        
        public IsysStatusSVCClient() {
        }
        
        public IsysStatusSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsysStatusSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsysStatusSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsysStatusSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.sysStatus model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.sysStatus model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.sysStatus model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.sysStatus model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.sysStatus Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.sysStatus> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.sysStatus[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.sysStatus[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
