//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.mesRouteDetailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mesRouteDetailService.ImesRouteDetailSVC")]
    public interface ImesRouteDetailSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteDetailSVC/Insert", ReplyAction="http://tempuri.org/ImesRouteDetailSVC/InsertResponse")]
        int Insert(App.Model.mesRouteDetail model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteDetailSVC/Insert", ReplyAction="http://tempuri.org/ImesRouteDetailSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesRouteDetail model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteDetailSVC/Delete", ReplyAction="http://tempuri.org/ImesRouteDetailSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteDetailSVC/Delete", ReplyAction="http://tempuri.org/ImesRouteDetailSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteDetailSVC/Update", ReplyAction="http://tempuri.org/ImesRouteDetailSVC/UpdateResponse")]
        bool Update(App.Model.mesRouteDetail model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteDetailSVC/Update", ReplyAction="http://tempuri.org/ImesRouteDetailSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesRouteDetail model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteDetailSVC/Get", ReplyAction="http://tempuri.org/ImesRouteDetailSVC/GetResponse")]
        App.Model.mesRouteDetail Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteDetailSVC/Get", ReplyAction="http://tempuri.org/ImesRouteDetailSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.mesRouteDetail> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteDetailSVC/ListAll", ReplyAction="http://tempuri.org/ImesRouteDetailSVC/ListAllResponse")]
        App.Model.mesRouteDetail[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteDetailSVC/ListAll", ReplyAction="http://tempuri.org/ImesRouteDetailSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.mesRouteDetail[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImesRouteDetailSVCChannel : App.MyMES.mesRouteDetailService.ImesRouteDetailSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImesRouteDetailSVCClient : System.ServiceModel.ClientBase<App.MyMES.mesRouteDetailService.ImesRouteDetailSVC>, App.MyMES.mesRouteDetailService.ImesRouteDetailSVC {
        
        public ImesRouteDetailSVCClient() {
        }
        
        public ImesRouteDetailSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImesRouteDetailSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesRouteDetailSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesRouteDetailSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.mesRouteDetail model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesRouteDetail model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.mesRouteDetail model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesRouteDetail model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.mesRouteDetail Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesRouteDetail> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.mesRouteDetail[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesRouteDetail[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
