//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.mesSerialNumberService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mesSerialNumberService.ImesSerialNumberSVC")]
    public interface ImesSerialNumberSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesSerialNumberSVC/Insert", ReplyAction="http://tempuri.org/ImesSerialNumberSVC/InsertResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.mesSerialNumber[]))]
        int Insert(App.Model.mesSerialNumber model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesSerialNumberSVC/Insert", ReplyAction="http://tempuri.org/ImesSerialNumberSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesSerialNumber model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesSerialNumberSVC/Delete", ReplyAction="http://tempuri.org/ImesSerialNumberSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesSerialNumberSVC/Delete", ReplyAction="http://tempuri.org/ImesSerialNumberSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesSerialNumberSVC/Update", ReplyAction="http://tempuri.org/ImesSerialNumberSVC/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.mesSerialNumber[]))]
        bool Update(App.Model.mesSerialNumber model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesSerialNumberSVC/Update", ReplyAction="http://tempuri.org/ImesSerialNumberSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesSerialNumber model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesSerialNumberSVC/Get", ReplyAction="http://tempuri.org/ImesSerialNumberSVC/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.mesSerialNumber[]))]
        App.Model.mesSerialNumber Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesSerialNumberSVC/Get", ReplyAction="http://tempuri.org/ImesSerialNumberSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.mesSerialNumber> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesSerialNumberSVC/ListAll", ReplyAction="http://tempuri.org/ImesSerialNumberSVC/ListAllResponse")]
        App.Model.mesSerialNumber[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesSerialNumberSVC/ListAll", ReplyAction="http://tempuri.org/ImesSerialNumberSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.mesSerialNumber[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImesSerialNumberSVCChannel : App.MyMES.mesSerialNumberService.ImesSerialNumberSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImesSerialNumberSVCClient : System.ServiceModel.ClientBase<App.MyMES.mesSerialNumberService.ImesSerialNumberSVC>, App.MyMES.mesSerialNumberService.ImesSerialNumberSVC {
        
        public ImesSerialNumberSVCClient() {
        }
        
        public ImesSerialNumberSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImesSerialNumberSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesSerialNumberSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesSerialNumberSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.mesSerialNumber model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesSerialNumber model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.mesSerialNumber model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesSerialNumber model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.mesSerialNumber Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesSerialNumber> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.mesSerialNumber[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesSerialNumber[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
