//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.luDefectService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="luDefectService.IluDefectSVC")]
    public interface IluDefectSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluDefectSVC/Insert", ReplyAction="http://tempuri.org/IluDefectSVC/InsertResponse")]
        string Insert(App.Model.luDefect model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluDefectSVC/Insert", ReplyAction="http://tempuri.org/IluDefectSVC/InsertResponse")]
        System.Threading.Tasks.Task<string> InsertAsync(App.Model.luDefect model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluDefectSVC/Delete", ReplyAction="http://tempuri.org/IluDefectSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluDefectSVC/Delete", ReplyAction="http://tempuri.org/IluDefectSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluDefectSVC/Update", ReplyAction="http://tempuri.org/IluDefectSVC/UpdateResponse")]
        string Update(App.Model.luDefect model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluDefectSVC/Update", ReplyAction="http://tempuri.org/IluDefectSVC/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(App.Model.luDefect model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluDefectSVC/Get", ReplyAction="http://tempuri.org/IluDefectSVC/GetResponse")]
        App.Model.luDefect Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluDefectSVC/Get", ReplyAction="http://tempuri.org/IluDefectSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.luDefect> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluDefectSVC/ListAll", ReplyAction="http://tempuri.org/IluDefectSVC/ListAllResponse")]
        App.Model.luDefect[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluDefectSVC/ListAll", ReplyAction="http://tempuri.org/IluDefectSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.luDefect[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IluDefectSVCChannel : App.MyMES.luDefectService.IluDefectSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IluDefectSVCClient : System.ServiceModel.ClientBase<App.MyMES.luDefectService.IluDefectSVC>, App.MyMES.luDefectService.IluDefectSVC {
        
        public IluDefectSVCClient() {
        }
        
        public IluDefectSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IluDefectSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluDefectSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluDefectSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Insert(App.Model.luDefect model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<string> InsertAsync(App.Model.luDefect model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public string Update(App.Model.luDefect model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(App.Model.luDefect model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.luDefect Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.luDefect> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.luDefect[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.luDefect[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
