//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.luSerialNumberTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="luSerialNumberTypeService.IluSerialNumberTypeSVC")]
    public interface IluSerialNumberTypeSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluSerialNumberTypeSVC/Insert", ReplyAction="http://tempuri.org/IluSerialNumberTypeSVC/InsertResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.luSerialNumberType[]))]
        int Insert(App.Model.luSerialNumberType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluSerialNumberTypeSVC/Insert", ReplyAction="http://tempuri.org/IluSerialNumberTypeSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.luSerialNumberType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluSerialNumberTypeSVC/Delete", ReplyAction="http://tempuri.org/IluSerialNumberTypeSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluSerialNumberTypeSVC/Delete", ReplyAction="http://tempuri.org/IluSerialNumberTypeSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluSerialNumberTypeSVC/Update", ReplyAction="http://tempuri.org/IluSerialNumberTypeSVC/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.luSerialNumberType[]))]
        bool Update(App.Model.luSerialNumberType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluSerialNumberTypeSVC/Update", ReplyAction="http://tempuri.org/IluSerialNumberTypeSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.luSerialNumberType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluSerialNumberTypeSVC/Get", ReplyAction="http://tempuri.org/IluSerialNumberTypeSVC/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.luSerialNumberType[]))]
        App.Model.luSerialNumberType Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluSerialNumberTypeSVC/Get", ReplyAction="http://tempuri.org/IluSerialNumberTypeSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.luSerialNumberType> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluSerialNumberTypeSVC/ListAll", ReplyAction="http://tempuri.org/IluSerialNumberTypeSVC/ListAllResponse")]
        App.Model.luSerialNumberType[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluSerialNumberTypeSVC/ListAll", ReplyAction="http://tempuri.org/IluSerialNumberTypeSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.luSerialNumberType[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IluSerialNumberTypeSVCChannel : App.MyMES.luSerialNumberTypeService.IluSerialNumberTypeSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IluSerialNumberTypeSVCClient : System.ServiceModel.ClientBase<App.MyMES.luSerialNumberTypeService.IluSerialNumberTypeSVC>, App.MyMES.luSerialNumberTypeService.IluSerialNumberTypeSVC {
        
        public IluSerialNumberTypeSVCClient() {
        }
        
        public IluSerialNumberTypeSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IluSerialNumberTypeSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluSerialNumberTypeSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluSerialNumberTypeSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.luSerialNumberType model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.luSerialNumberType model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.luSerialNumberType model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.luSerialNumberType model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.luSerialNumberType Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.luSerialNumberType> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.luSerialNumberType[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.luSerialNumberType[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
