//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.luMachineFamilyTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="luMachineFamilyTypeService.IluMachineFamilyTypeSVC")]
    public interface IluMachineFamilyTypeSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilyTypeSVC/Insert", ReplyAction="http://tempuri.org/IluMachineFamilyTypeSVC/InsertResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.luMachineFamilyType[]))]
        int Insert(App.Model.luMachineFamilyType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilyTypeSVC/Insert", ReplyAction="http://tempuri.org/IluMachineFamilyTypeSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.luMachineFamilyType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilyTypeSVC/Delete", ReplyAction="http://tempuri.org/IluMachineFamilyTypeSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilyTypeSVC/Delete", ReplyAction="http://tempuri.org/IluMachineFamilyTypeSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilyTypeSVC/Update", ReplyAction="http://tempuri.org/IluMachineFamilyTypeSVC/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.luMachineFamilyType[]))]
        bool Update(App.Model.luMachineFamilyType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilyTypeSVC/Update", ReplyAction="http://tempuri.org/IluMachineFamilyTypeSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.luMachineFamilyType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilyTypeSVC/Get", ReplyAction="http://tempuri.org/IluMachineFamilyTypeSVC/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.luMachineFamilyType[]))]
        App.Model.luMachineFamilyType Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilyTypeSVC/Get", ReplyAction="http://tempuri.org/IluMachineFamilyTypeSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.luMachineFamilyType> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilyTypeSVC/ListAll", ReplyAction="http://tempuri.org/IluMachineFamilyTypeSVC/ListAllResponse")]
        App.Model.luMachineFamilyType[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilyTypeSVC/ListAll", ReplyAction="http://tempuri.org/IluMachineFamilyTypeSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.luMachineFamilyType[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IluMachineFamilyTypeSVCChannel : App.MyMES.luMachineFamilyTypeService.IluMachineFamilyTypeSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IluMachineFamilyTypeSVCClient : System.ServiceModel.ClientBase<App.MyMES.luMachineFamilyTypeService.IluMachineFamilyTypeSVC>, App.MyMES.luMachineFamilyTypeService.IluMachineFamilyTypeSVC {
        
        public IluMachineFamilyTypeSVCClient() {
        }
        
        public IluMachineFamilyTypeSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IluMachineFamilyTypeSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluMachineFamilyTypeSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluMachineFamilyTypeSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.luMachineFamilyType model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.luMachineFamilyType model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.luMachineFamilyType model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.luMachineFamilyType model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.luMachineFamilyType Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.luMachineFamilyType> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.luMachineFamilyType[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.luMachineFamilyType[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
