//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.mesProductStructureService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mesProductStructureService.ImesProductStructureSVC")]
    public interface ImesProductStructureSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesProductStructureSVC/Insert", ReplyAction="http://tempuri.org/ImesProductStructureSVC/InsertResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.mesProductStructure[]))]
        int Insert(App.Model.mesProductStructure model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesProductStructureSVC/Insert", ReplyAction="http://tempuri.org/ImesProductStructureSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesProductStructure model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesProductStructureSVC/Delete", ReplyAction="http://tempuri.org/ImesProductStructureSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesProductStructureSVC/Delete", ReplyAction="http://tempuri.org/ImesProductStructureSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesProductStructureSVC/Update", ReplyAction="http://tempuri.org/ImesProductStructureSVC/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.mesProductStructure[]))]
        bool Update(App.Model.mesProductStructure model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesProductStructureSVC/Update", ReplyAction="http://tempuri.org/ImesProductStructureSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesProductStructure model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesProductStructureSVC/Get", ReplyAction="http://tempuri.org/ImesProductStructureSVC/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.mesProductStructure[]))]
        App.Model.mesProductStructure Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesProductStructureSVC/Get", ReplyAction="http://tempuri.org/ImesProductStructureSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.mesProductStructure> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesProductStructureSVC/ListAll", ReplyAction="http://tempuri.org/ImesProductStructureSVC/ListAllResponse")]
        App.Model.mesProductStructure[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesProductStructureSVC/ListAll", ReplyAction="http://tempuri.org/ImesProductStructureSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.mesProductStructure[]> ListAllAsync(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesProductStructureSVC/GetBOMStructure", ReplyAction="http://tempuri.org/ImesProductStructureSVC/GetBOMStructureResponse")]
        System.Data.DataSet GetBOMStructure(string ParentPartID, string PartID, string StationTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesProductStructureSVC/GetBOMStructure", ReplyAction="http://tempuri.org/ImesProductStructureSVC/GetBOMStructureResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBOMStructureAsync(string ParentPartID, string PartID, string StationTypeID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImesProductStructureSVCChannel : App.MyMES.mesProductStructureService.ImesProductStructureSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImesProductStructureSVCClient : System.ServiceModel.ClientBase<App.MyMES.mesProductStructureService.ImesProductStructureSVC>, App.MyMES.mesProductStructureService.ImesProductStructureSVC {
        
        public ImesProductStructureSVCClient() {
        }
        
        public ImesProductStructureSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImesProductStructureSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesProductStructureSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesProductStructureSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.mesProductStructure model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesProductStructure model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.mesProductStructure model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesProductStructure model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.mesProductStructure Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesProductStructure> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.mesProductStructure[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesProductStructure[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
        
        public System.Data.DataSet GetBOMStructure(string ParentPartID, string PartID, string StationTypeID) {
            return base.Channel.GetBOMStructure(ParentPartID, PartID, StationTypeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBOMStructureAsync(string ParentPartID, string PartID, string StationTypeID) {
            return base.Channel.GetBOMStructureAsync(ParentPartID, PartID, StationTypeID);
        }
    }
}
