//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.mesPackageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mesPackageService.ImesPackageSVC")]
    public interface ImesPackageSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPackageSVC/Insert", ReplyAction="http://tempuri.org/ImesPackageSVC/InsertResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.mesPackage[]))]
        int Insert(App.Model.mesPackage model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPackageSVC/Insert", ReplyAction="http://tempuri.org/ImesPackageSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesPackage model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPackageSVC/Delete", ReplyAction="http://tempuri.org/ImesPackageSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPackageSVC/Delete", ReplyAction="http://tempuri.org/ImesPackageSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPackageSVC/Update", ReplyAction="http://tempuri.org/ImesPackageSVC/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.mesPackage[]))]
        bool Update(App.Model.mesPackage model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPackageSVC/Update", ReplyAction="http://tempuri.org/ImesPackageSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesPackage model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPackageSVC/Get", ReplyAction="http://tempuri.org/ImesPackageSVC/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.mesPackage[]))]
        App.Model.mesPackage Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPackageSVC/Get", ReplyAction="http://tempuri.org/ImesPackageSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.mesPackage> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPackageSVC/ListAll", ReplyAction="http://tempuri.org/ImesPackageSVC/ListAllResponse")]
        App.Model.mesPackage[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPackageSVC/ListAll", ReplyAction="http://tempuri.org/ImesPackageSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.mesPackage[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImesPackageSVCChannel : App.MyMES.mesPackageService.ImesPackageSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImesPackageSVCClient : System.ServiceModel.ClientBase<App.MyMES.mesPackageService.ImesPackageSVC>, App.MyMES.mesPackageService.ImesPackageSVC {
        
        public ImesPackageSVCClient() {
        }
        
        public ImesPackageSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImesPackageSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesPackageSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesPackageSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.mesPackage model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesPackage model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.mesPackage model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesPackage model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.mesPackage Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesPackage> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.mesPackage[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesPackage[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
