//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.luPartFamilyTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="luPartFamilyTypeService.IluPartFamilyTypeSVC")]
    public interface IluPartFamilyTypeSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluPartFamilyTypeSVC/Insert", ReplyAction="http://tempuri.org/IluPartFamilyTypeSVC/InsertResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.luPartFamilyType[]))]
        int Insert(App.Model.luPartFamilyType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluPartFamilyTypeSVC/Insert", ReplyAction="http://tempuri.org/IluPartFamilyTypeSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.luPartFamilyType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluPartFamilyTypeSVC/Delete", ReplyAction="http://tempuri.org/IluPartFamilyTypeSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluPartFamilyTypeSVC/Delete", ReplyAction="http://tempuri.org/IluPartFamilyTypeSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluPartFamilyTypeSVC/Update", ReplyAction="http://tempuri.org/IluPartFamilyTypeSVC/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.luPartFamilyType[]))]
        bool Update(App.Model.luPartFamilyType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluPartFamilyTypeSVC/Update", ReplyAction="http://tempuri.org/IluPartFamilyTypeSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.luPartFamilyType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluPartFamilyTypeSVC/Get", ReplyAction="http://tempuri.org/IluPartFamilyTypeSVC/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.luPartFamilyType[]))]
        App.Model.luPartFamilyType Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluPartFamilyTypeSVC/Get", ReplyAction="http://tempuri.org/IluPartFamilyTypeSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.luPartFamilyType> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluPartFamilyTypeSVC/ListAll", ReplyAction="http://tempuri.org/IluPartFamilyTypeSVC/ListAllResponse")]
        App.Model.luPartFamilyType[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluPartFamilyTypeSVC/ListAll", ReplyAction="http://tempuri.org/IluPartFamilyTypeSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.luPartFamilyType[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IluPartFamilyTypeSVCChannel : App.MyMES.luPartFamilyTypeService.IluPartFamilyTypeSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IluPartFamilyTypeSVCClient : System.ServiceModel.ClientBase<App.MyMES.luPartFamilyTypeService.IluPartFamilyTypeSVC>, App.MyMES.luPartFamilyTypeService.IluPartFamilyTypeSVC {
        
        public IluPartFamilyTypeSVCClient() {
        }
        
        public IluPartFamilyTypeSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IluPartFamilyTypeSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluPartFamilyTypeSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluPartFamilyTypeSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.luPartFamilyType model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.luPartFamilyType model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.luPartFamilyType model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.luPartFamilyType model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.luPartFamilyType Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.luPartFamilyType> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.luPartFamilyType[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.luPartFamilyType[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
