//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.mesRouteMachineMapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mesRouteMachineMapService.ImesRouteMachineMapSVC")]
    public interface ImesRouteMachineMapSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteMachineMapSVC/Insert", ReplyAction="http://tempuri.org/ImesRouteMachineMapSVC/InsertResponse")]
        int Insert(App.Model.mesRouteMachineMap model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteMachineMapSVC/Insert", ReplyAction="http://tempuri.org/ImesRouteMachineMapSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesRouteMachineMap model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteMachineMapSVC/Delete", ReplyAction="http://tempuri.org/ImesRouteMachineMapSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteMachineMapSVC/Delete", ReplyAction="http://tempuri.org/ImesRouteMachineMapSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteMachineMapSVC/Update", ReplyAction="http://tempuri.org/ImesRouteMachineMapSVC/UpdateResponse")]
        bool Update(App.Model.mesRouteMachineMap model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteMachineMapSVC/Update", ReplyAction="http://tempuri.org/ImesRouteMachineMapSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesRouteMachineMap model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteMachineMapSVC/Get", ReplyAction="http://tempuri.org/ImesRouteMachineMapSVC/GetResponse")]
        App.Model.mesRouteMachineMap Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteMachineMapSVC/Get", ReplyAction="http://tempuri.org/ImesRouteMachineMapSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.mesRouteMachineMap> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteMachineMapSVC/ListAll", ReplyAction="http://tempuri.org/ImesRouteMachineMapSVC/ListAllResponse")]
        App.Model.mesRouteMachineMap[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesRouteMachineMapSVC/ListAll", ReplyAction="http://tempuri.org/ImesRouteMachineMapSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.mesRouteMachineMap[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImesRouteMachineMapSVCChannel : App.MyMES.mesRouteMachineMapService.ImesRouteMachineMapSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImesRouteMachineMapSVCClient : System.ServiceModel.ClientBase<App.MyMES.mesRouteMachineMapService.ImesRouteMachineMapSVC>, App.MyMES.mesRouteMachineMapService.ImesRouteMachineMapSVC {
        
        public ImesRouteMachineMapSVCClient() {
        }
        
        public ImesRouteMachineMapSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImesRouteMachineMapSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesRouteMachineMapSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesRouteMachineMapSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.mesRouteMachineMap model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesRouteMachineMap model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.mesRouteMachineMap model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesRouteMachineMap model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.mesRouteMachineMap Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesRouteMachineMap> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.mesRouteMachineMap[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesRouteMachineMap[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
