//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.mesStationTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mesStationTypeService.ImesStationTypeSVC")]
    public interface ImesStationTypeSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesStationTypeSVC/Insert", ReplyAction="http://tempuri.org/ImesStationTypeSVC/InsertResponse")]
        int Insert(App.Model.mesStationType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesStationTypeSVC/Insert", ReplyAction="http://tempuri.org/ImesStationTypeSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesStationType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesStationTypeSVC/Delete", ReplyAction="http://tempuri.org/ImesStationTypeSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesStationTypeSVC/Delete", ReplyAction="http://tempuri.org/ImesStationTypeSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesStationTypeSVC/Update", ReplyAction="http://tempuri.org/ImesStationTypeSVC/UpdateResponse")]
        bool Update(App.Model.mesStationType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesStationTypeSVC/Update", ReplyAction="http://tempuri.org/ImesStationTypeSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesStationType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesStationTypeSVC/Get", ReplyAction="http://tempuri.org/ImesStationTypeSVC/GetResponse")]
        App.Model.mesStationType Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesStationTypeSVC/Get", ReplyAction="http://tempuri.org/ImesStationTypeSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.mesStationType> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesStationTypeSVC/ListAll", ReplyAction="http://tempuri.org/ImesStationTypeSVC/ListAllResponse")]
        App.Model.mesStationType[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesStationTypeSVC/ListAll", ReplyAction="http://tempuri.org/ImesStationTypeSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.mesStationType[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImesStationTypeSVCChannel : App.MyMES.mesStationTypeService.ImesStationTypeSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImesStationTypeSVCClient : System.ServiceModel.ClientBase<App.MyMES.mesStationTypeService.ImesStationTypeSVC>, App.MyMES.mesStationTypeService.ImesStationTypeSVC {
        
        public ImesStationTypeSVCClient() {
        }
        
        public ImesStationTypeSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImesStationTypeSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesStationTypeSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesStationTypeSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.mesStationType model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesStationType model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.mesStationType model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesStationType model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.mesStationType Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesStationType> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.mesStationType[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesStationType[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
