//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.luMachineFamilyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="luMachineFamilyService.IluMachineFamilySVC")]
    public interface IluMachineFamilySVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilySVC/Insert", ReplyAction="http://tempuri.org/IluMachineFamilySVC/InsertResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.luMachineFamily[]))]
        int Insert(App.Model.luMachineFamily model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilySVC/Insert", ReplyAction="http://tempuri.org/IluMachineFamilySVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.luMachineFamily model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilySVC/Delete", ReplyAction="http://tempuri.org/IluMachineFamilySVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilySVC/Delete", ReplyAction="http://tempuri.org/IluMachineFamilySVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilySVC/Update", ReplyAction="http://tempuri.org/IluMachineFamilySVC/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.luMachineFamily[]))]
        bool Update(App.Model.luMachineFamily model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilySVC/Update", ReplyAction="http://tempuri.org/IluMachineFamilySVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.luMachineFamily model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilySVC/Get", ReplyAction="http://tempuri.org/IluMachineFamilySVC/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.luMachineFamily[]))]
        App.Model.luMachineFamily Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilySVC/Get", ReplyAction="http://tempuri.org/IluMachineFamilySVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.luMachineFamily> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilySVC/ListAll", ReplyAction="http://tempuri.org/IluMachineFamilySVC/ListAllResponse")]
        App.Model.luMachineFamily[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluMachineFamilySVC/ListAll", ReplyAction="http://tempuri.org/IluMachineFamilySVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.luMachineFamily[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IluMachineFamilySVCChannel : App.MyMES.luMachineFamilyService.IluMachineFamilySVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IluMachineFamilySVCClient : System.ServiceModel.ClientBase<App.MyMES.luMachineFamilyService.IluMachineFamilySVC>, App.MyMES.luMachineFamilyService.IluMachineFamilySVC {
        
        public IluMachineFamilySVCClient() {
        }
        
        public IluMachineFamilySVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IluMachineFamilySVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluMachineFamilySVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluMachineFamilySVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.luMachineFamily model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.luMachineFamily model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.luMachineFamily model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.luMachineFamily model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.luMachineFamily Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.luMachineFamily> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.luMachineFamily[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.luMachineFamily[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
