//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.luApplicationTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="luApplicationTypeService.IluApplicationTypeSVC")]
    public interface IluApplicationTypeSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluApplicationTypeSVC/Insert", ReplyAction="http://tempuri.org/IluApplicationTypeSVC/InsertResponse")]
        int Insert(App.Model.luApplicationType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluApplicationTypeSVC/Insert", ReplyAction="http://tempuri.org/IluApplicationTypeSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.luApplicationType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluApplicationTypeSVC/Delete", ReplyAction="http://tempuri.org/IluApplicationTypeSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluApplicationTypeSVC/Delete", ReplyAction="http://tempuri.org/IluApplicationTypeSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluApplicationTypeSVC/Update", ReplyAction="http://tempuri.org/IluApplicationTypeSVC/UpdateResponse")]
        bool Update(App.Model.luApplicationType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluApplicationTypeSVC/Update", ReplyAction="http://tempuri.org/IluApplicationTypeSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.luApplicationType model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluApplicationTypeSVC/Get", ReplyAction="http://tempuri.org/IluApplicationTypeSVC/GetResponse")]
        App.Model.luApplicationType Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluApplicationTypeSVC/Get", ReplyAction="http://tempuri.org/IluApplicationTypeSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.luApplicationType> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluApplicationTypeSVC/ListAll", ReplyAction="http://tempuri.org/IluApplicationTypeSVC/ListAllResponse")]
        App.Model.luApplicationType[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluApplicationTypeSVC/ListAll", ReplyAction="http://tempuri.org/IluApplicationTypeSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.luApplicationType[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IluApplicationTypeSVCChannel : App.MyMES.luApplicationTypeService.IluApplicationTypeSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IluApplicationTypeSVCClient : System.ServiceModel.ClientBase<App.MyMES.luApplicationTypeService.IluApplicationTypeSVC>, App.MyMES.luApplicationTypeService.IluApplicationTypeSVC {
        
        public IluApplicationTypeSVCClient() {
        }
        
        public IluApplicationTypeSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IluApplicationTypeSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluApplicationTypeSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluApplicationTypeSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.luApplicationType model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.luApplicationType model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.luApplicationType model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.luApplicationType model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.luApplicationType Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.luApplicationType> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.luApplicationType[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.luApplicationType[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
