//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.mesPartDetailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mesPartDetailService.ImesPartDetailSVC")]
    public interface ImesPartDetailSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartDetailSVC/Insert", ReplyAction="http://tempuri.org/ImesPartDetailSVC/InsertResponse")]
        int Insert(App.Model.mesPartDetail model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartDetailSVC/Insert", ReplyAction="http://tempuri.org/ImesPartDetailSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesPartDetail model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartDetailSVC/Delete", ReplyAction="http://tempuri.org/ImesPartDetailSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartDetailSVC/Delete", ReplyAction="http://tempuri.org/ImesPartDetailSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartDetailSVC/Update", ReplyAction="http://tempuri.org/ImesPartDetailSVC/UpdateResponse")]
        bool Update(App.Model.mesPartDetail model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartDetailSVC/Update", ReplyAction="http://tempuri.org/ImesPartDetailSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesPartDetail model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartDetailSVC/Get", ReplyAction="http://tempuri.org/ImesPartDetailSVC/GetResponse")]
        App.Model.mesPartDetail Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartDetailSVC/Get", ReplyAction="http://tempuri.org/ImesPartDetailSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.mesPartDetail> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartDetailSVC/ListAll", ReplyAction="http://tempuri.org/ImesPartDetailSVC/ListAllResponse")]
        App.Model.mesPartDetail[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartDetailSVC/ListAll", ReplyAction="http://tempuri.org/ImesPartDetailSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.mesPartDetail[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImesPartDetailSVCChannel : App.MyMES.mesPartDetailService.ImesPartDetailSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImesPartDetailSVCClient : System.ServiceModel.ClientBase<App.MyMES.mesPartDetailService.ImesPartDetailSVC>, App.MyMES.mesPartDetailService.ImesPartDetailSVC {
        
        public ImesPartDetailSVCClient() {
        }
        
        public ImesPartDetailSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImesPartDetailSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesPartDetailSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesPartDetailSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.mesPartDetail model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesPartDetail model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.mesPartDetail model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesPartDetail model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.mesPartDetail Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesPartDetail> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.mesPartDetail[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesPartDetail[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
