//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.luEmployeeGroupService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="luEmployeeGroupService.IluEmployeeGroupSVC")]
    public interface IluEmployeeGroupSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluEmployeeGroupSVC/Insert", ReplyAction="http://tempuri.org/IluEmployeeGroupSVC/InsertResponse")]
        int Insert(App.Model.luEmployeeGroup model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluEmployeeGroupSVC/Insert", ReplyAction="http://tempuri.org/IluEmployeeGroupSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.luEmployeeGroup model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluEmployeeGroupSVC/Delete", ReplyAction="http://tempuri.org/IluEmployeeGroupSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluEmployeeGroupSVC/Delete", ReplyAction="http://tempuri.org/IluEmployeeGroupSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluEmployeeGroupSVC/Update", ReplyAction="http://tempuri.org/IluEmployeeGroupSVC/UpdateResponse")]
        bool Update(App.Model.luEmployeeGroup model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluEmployeeGroupSVC/Update", ReplyAction="http://tempuri.org/IluEmployeeGroupSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.luEmployeeGroup model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluEmployeeGroupSVC/Get", ReplyAction="http://tempuri.org/IluEmployeeGroupSVC/GetResponse")]
        App.Model.luEmployeeGroup Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluEmployeeGroupSVC/Get", ReplyAction="http://tempuri.org/IluEmployeeGroupSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.luEmployeeGroup> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluEmployeeGroupSVC/ListAll", ReplyAction="http://tempuri.org/IluEmployeeGroupSVC/ListAllResponse")]
        App.Model.luEmployeeGroup[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IluEmployeeGroupSVC/ListAll", ReplyAction="http://tempuri.org/IluEmployeeGroupSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.luEmployeeGroup[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IluEmployeeGroupSVCChannel : App.MyMES.luEmployeeGroupService.IluEmployeeGroupSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IluEmployeeGroupSVCClient : System.ServiceModel.ClientBase<App.MyMES.luEmployeeGroupService.IluEmployeeGroupSVC>, App.MyMES.luEmployeeGroupService.IluEmployeeGroupSVC {
        
        public IluEmployeeGroupSVCClient() {
        }
        
        public IluEmployeeGroupSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IluEmployeeGroupSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluEmployeeGroupSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluEmployeeGroupSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.luEmployeeGroup model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.luEmployeeGroup model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.luEmployeeGroup model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.luEmployeeGroup model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.luEmployeeGroup Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.luEmployeeGroup> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.luEmployeeGroup[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.luEmployeeGroup[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
