//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MyMES.mesPartService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mesPartService.ImesPartSVC")]
    public interface ImesPartSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartSVC/Insert", ReplyAction="http://tempuri.org/ImesPartSVC/InsertResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.mesPart[]))]
        int Insert(App.Model.mesPart model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartSVC/Insert", ReplyAction="http://tempuri.org/ImesPartSVC/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesPart model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartSVC/Delete", ReplyAction="http://tempuri.org/ImesPartSVC/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartSVC/Delete", ReplyAction="http://tempuri.org/ImesPartSVC/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartSVC/Update", ReplyAction="http://tempuri.org/ImesPartSVC/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.mesPart[]))]
        bool Update(App.Model.mesPart model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartSVC/Update", ReplyAction="http://tempuri.org/ImesPartSVC/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesPart model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartSVC/Get", ReplyAction="http://tempuri.org/ImesPartSVC/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(App.Model.mesPart[]))]
        App.Model.mesPart Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartSVC/Get", ReplyAction="http://tempuri.org/ImesPartSVC/GetResponse")]
        System.Threading.Tasks.Task<App.Model.mesPart> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartSVC/ListAll", ReplyAction="http://tempuri.org/ImesPartSVC/ListAllResponse")]
        App.Model.mesPart[] ListAll(string S_Where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImesPartSVC/ListAll", ReplyAction="http://tempuri.org/ImesPartSVC/ListAllResponse")]
        System.Threading.Tasks.Task<App.Model.mesPart[]> ListAllAsync(string S_Where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImesPartSVCChannel : App.MyMES.mesPartService.ImesPartSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImesPartSVCClient : System.ServiceModel.ClientBase<App.MyMES.mesPartService.ImesPartSVC>, App.MyMES.mesPartService.ImesPartSVC {
        
        public ImesPartSVCClient() {
        }
        
        public ImesPartSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImesPartSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesPartSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImesPartSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(App.Model.mesPart model) {
            return base.Channel.Insert(model);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(App.Model.mesPart model) {
            return base.Channel.InsertAsync(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public bool Update(App.Model.mesPart model) {
            return base.Channel.Update(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(App.Model.mesPart model) {
            return base.Channel.UpdateAsync(model);
        }
        
        public App.Model.mesPart Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesPart> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public App.Model.mesPart[] ListAll(string S_Where) {
            return base.Channel.ListAll(S_Where);
        }
        
        public System.Threading.Tasks.Task<App.Model.mesPart[]> ListAllAsync(string S_Where) {
            return base.Channel.ListAllAsync(S_Where);
        }
    }
}
